/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"
#include "uart.h"
#include "adc.h"
#include "i2c.h"
#include "i2c_lcd.h"
#include "switch.h"
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	char str[32];
	uint16_t val;
	SystemInit();

	LcdInit();
	SwitchInit(SWITCH);
	ADC_Init();
	//UartInit(BAUD_9600);
	//UartPuts("DESD ADC Demo...\r\n");
	LcdPuts(LCD_LINE1, "LDR");
	while(1) {

		while(SwitchGetState(SWITCH))
		{
				// Blink the Led
		val = ADC_GetValue();
				sprintf(str, "ADC=%d\r\n", val);
				//UartPuts(str);
				// wait until switch interrupt generated

				LcdPuts(LCD_LINE2, str);
				DelayMs(1000);
		}

	}
	return 0;
}
